<a href="https://colab.research.google.com/github/mars241/DatasetP4/blob/main/NOTES_02_01_Introduction_au_calcul_numerique_avec_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy ou `Numerical Python` est la libraire Python pour le calcul scientifique. Numpy est la base de plusieurs libraires comme Pandas scipy, sklearn et a inspiré les libraires comme PyTorch et Tensorlow. Vous pouvez aller sur https://numpy.org/ pour avoir une idée de tous les sous domaines scientifiques dans lesquels il est utilisé. On peut l'importer de cette manière :

In [ ]:
import numpy as np

# Tableaux Numpy : Les bases

Python ne supporte pas des types de données multi-dimensionnelles. Un tableau Numpy peut être non seulement multidimensionnel mais permet aussi des opérations vectorielles ou matricielles.

## Création d'un Tableau Numpy

In [ ]:
data = np.array([
    [1, 5, 9],
    [8, 9, 7]
])

Pour créer un tableau numpy, nous utilisons la fonction `array` et lui donnons une liste d'éléments. Notre variable data contient un tableau de dimension 2

In [ ]:
data.ndim

2

data contient, un tableau avec 2 lignes et 3 colonnes. Chaque ligne est une liste et le nombre d'éléments dans une liste est le nombre de colonnes:

In [ ]:
data.shape

(2, 3)

data contient 6 éléments:

In [ ]:
data.size

6

## Comprendre les attributs des tableaux Numpy

Créeons le plus simple tableau numpy possible.

In [ ]:
data_un = np.array([1])

In [ ]:
data_un.ndim

1

In [ ]:
data_un.shape

(1,)

In [ ]:
data_un.size

1

data_un contient un nombre, qu'on peut appeler un scalaire. Il a donc un size de 1, puisqu'il s'agit d'un seul élément. Il est de dimension 1 et a un seul élément sur cette dimension

Créons un autre tableau

In [ ]:
data_un = np.array([1, 5, 6])

Prenez le temps de deviner le ndim, shape et size de ce tableau.

Combien d'éléments dans ce tableau ? 3

In [ ]:
data_un.size

3

Ce tableau a combien de dimensions ?

In [ ]:
data_un.ndim

1

Combien d'éléments sur cette seule dimension ?

In [ ]:
data_un.shape

(3,)

Mettons la liste de data_un dans une autre liste :

In [ ]:
data_un = np.array([   [1, 5, 6]    ])

In [ ]:
data_un.ndim

2

In [ ]:
data_un.size

3

In [ ]:
data_un.shape # une ligne, 3 colonnes

(1, 3)

La taille du tuple `shape` est égale au nombre de dimensions. Le `size` est simplement égale au produit du nombre d'élément sur chaque dimension

Créons un tableau avec 2 listes à l'intérieur:  

In [ ]:
data_deux = np.array([   [1, 5, 6],
                         [9, 4, 7]    ])

On a là un tableau de 2 dimensions, 2 lignes, 3 colonnes donc 6 élements:

In [ ]:
data_deux.ndim

2

In [ ]:
data_deux.shape

(2, 3)

In [ ]:
data_deux.size

6

Quel est le shape, ndim et size du tableau suivant :

In [ ]:
data = np.array([   [1, 5, 6, 2],
                    [9, 4, 7, 8],
                    [0, 1, 0, 6]     ])

In [ ]:
data.size

In [ ]:
data.shape

In [ ]:
data.ndim

A quoi ressemblerait un tableau de dimension 3 ?

In [ ]:
data_trois  = np.array([
      [[1, 5, 9],
       [8, 9, 7]],

      [[2, 5, 9],
       [8, 9, 7]],

      [[13, 5, 9],
       [8, 9, 7]]
])

In [ ]:
data_trois.shape # 3 petits tableau de shape (2, 3)

(3, 2, 3)

In [ ]:
data_trois.ndim

3

In [ ]:
data_trois.size

18

Dans la suite de ce bootcamp, nous travaillerons beaucoup avec des tableaux de dimensions 2.

## Accéder à un élément d'un tableau

In [ ]:
v = np.array([1,5,9])

In [ ]:
v.shape

(3,)

In [ ]:
v[0]

1

In [ ]:
v[-1]

9

In [ ]:
v[1:]

array([5, 9])

In [ ]:
matrice = np.array([
    [1, 5, 9],
    [8, 6, 7]
])

In [ ]:
matrice[1, 1]

6

In [ ]:
matrice[0,2]

9

In [ ]:
matrice[1, 0]

8

In [ ]:
v2 = np.array([
    [1, 5, 9]
])

In [ ]:
v2[0, 1]

5

## Accéder à des sous-tableaux d'un tableau

In [ ]:
matrice

array([[1, 5, 9],
       [8, 6, 7]])

In [ ]:
matrice[0, 1: ]

array([5, 9])

In [ ]:
matrice[1, 1: ]

array([6, 7])

In [ ]:
matrice[0: , 1: ]

array([[5, 9],
       [6, 7]])

In [ ]:
matrice[: , 1: ]

array([[5, 9],
       [6, 7]])

In [ ]:
matrice = np.array([
   [1, 5, 9, 4, 6],
   [8, 9, 7, 5, 0],
   [3, 2, 0, 6, 2],
   [8, 6, 7, 8, 9]
])

In [ ]:
matrice = np.array([
      0  1  2  3  4
   0 [1, 5, 9, 4, 6],
   1 [8, 9, 7, 5, 0],
   2 [3, 2, 0, 6, 2],
   3 [8, 6, 7, 8, 9]
])

In [ ]:
matrice.shape

(4, 5)

In [ ]:
matrice[2, 3]

6

In [ ]:
matrice[1:, 2:]

array([[7, 5, 0],
       [0, 6, 2],
       [7, 8, 9]])

In [ ]:
matrice[1:3, 2:4]

array([[7, 5],
       [0, 6]])

In [ ]:
matrice[1:3 , 1:3]

array([[9, 7],
       [2, 0]])

In [ ]:
matrice = np.arange(9).reshape((3,3))

In [ ]:
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
matrice[0:2, 1:]

array([[1, 2],
       [4, 5]])

In [ ]:
matrice[1: , :2]

array([[3, 4],
       [6, 7]])

## Vue et non copie d'un tableau

In [ ]:
matrice = np.arange(9).reshape((3,3))
matrice

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Modifions le 5 en 9 :

In [ ]:
matrice[1, -1] = 9

In [ ]:
matrice

array([[0, 1, 2],
       [3, 4, 9],
       [6, 7, 8]])

sauvegardons une partie de la matrice dans une variable data

In [ ]:
data = matrice[:2, :2]

In [ ]:
data

array([[0, 1],
       [3, 4]])

Modifions date en transformant le 0 en 15

In [ ]:
data[0, 0] = 15

In [ ]:
data

array([[15,  1],
       [ 3,  4]])

Cette modification de data, modifie-t-elle aussi la matrice ?

In [ ]:
matrice

array([[15,  1,  2],
       [ 3,  4,  9],
       [ 6,  7,  8]])

La réponse est oui. data n'était donc pas une copie de matrice mais une vue

## Comment copier alors un tableau ?

In [ ]:
data = matrice[:2, :2].copy()

In [ ]:
data

array([[15,  1],
       [ 3,  4]])

In [ ]:
data[0, 0] = 30

In [ ]:
data

array([[30,  1],
       [ 3,  4]])

In [ ]:
matrice

array([[15,  1,  2],
       [ 3,  4,  9],
       [ 6,  7,  8]])

Cette fois-ci la modification se fait voir uniquement dans data puisque c'est une copie.

## Modifier la taille d'un tableau

In [ ]:
x = np.random.randint(100, size=(2, 5))
x

array([[84, 39, 21, 98, 60],
       [29, 89, 13,  3, 57]])

In [ ]:
x.shape

(2, 5)

In [ ]:
x.reshape((5, 2))

array([[84, 39],
       [21, 98],
       [60, 29],
       [89, 13],
       [ 3, 57]])

In [ ]:
u = np.array([1,5,6])
u.shape

(3,)

In [ ]:
u.reshape((1,3))

array([[1, 5, 6]])

In [ ]:
u.reshape((3, 1))

array([[1],
       [5],
       [6]])

In [ ]:
u.reshape((2, 3))

ValueError: cannot reshape array of size 3 into shape (2,3)

## Concatener des Tableaux

In [ ]:
u

array([1, 5, 6])

In [ ]:
v = np.array([7, 8, 9])

In [ ]:
tab = np.vstack([u, v])
tab

array([[1, 5, 6],
       [7, 8, 9]])

In [ ]:
tab.shape

(2, 3)

In [ ]:
np.hstack([u, v])

array([1, 5, 6, 7, 8, 9])

In [ ]:
a = np.array([5, 9, 25])
a.shape

(3,)

In [ ]:
a = a.reshape((1,3))
a

array([[ 5,  9, 25]])

In [ ]:
np.vstack([a, a])

array([[ 5,  9, 25],
       [ 5,  9, 25]])

In [ ]:
np.hstack([a, a])

array([[ 5,  9, 25,  5,  9, 25]])

In [ ]:
np.hstack([a, a]).shape

(1, 6)

# Calcul sur les tableaux avec Numpy

## Tableau mieux que les listes ?

In [ ]:
nombres = list(range(2, 9))
nombres

[2, 3, 4, 5, 6, 7, 8]

In [ ]:
output = np.empty(len(nombres))

In [ ]:
output

array([4.6662084e-310, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 3.1620201e-322])

In [ ]:
for i, n in enumerate(nombres):
  output[i] = 1 / n
output

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

In [ ]:
nombres_tab = np.array(nombres)
nombres_tab

array([2, 3, 4, 5, 6, 7, 8])

In [ ]:
1 / nombres_tab

array([0.5       , 0.33333333, 0.25      , 0.2       , 0.16666667,
       0.14285714, 0.125     ])

In [ ]:
import time

In [ ]:
nombres = list(range(2, 10_000_000))
output = np.empty(len(nombres))
debut = time.time()
for i, n in enumerate(nombres):
  output[i] = 1 / n
fin  = time.time()
print(fin-debut)

1.5880019664764404


In [ ]:
debut = time.time()
1 / np.arange(2, 10_000_000)
fin  = time.time()
print(fin-debut)

0.04231858253479004


## Vectorisation

In [ ]:
l = [5, 8, 9]
[n**2 for n in l]

[25, 64, 81]

In [ ]:
np.array(l) ** 2

array([25, 64, 81])

In [ ]:
np.array(l)  + 1.5

array([ 6.5,  9.5, 10.5])

# Aggregation

In [ ]:
l

[5, 8, 9]

In [ ]:
min(l)

5

In [ ]:
np.min(l)

5

In [ ]:
np.array(l).min()

5

In [ ]:
np.random.seed(0)
tab = np.random.randint(15, size=(5, 3))
tab

array([[12,  5,  0],
       [ 3, 11,  3],
       [ 7,  9,  3],
       [ 5,  2,  4],
       [ 7,  6,  8]])

In [ ]:
min(tab)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
np.min(tab)

0

In [ ]:
tab.min()

0

In [ ]:
np.min(tab, axis= 0) # Minimum de chaque colonne

array([3, 2, 0])

In [ ]:
np.min(tab, axis= 1) #Minimum de chaque ligne

array([0, 3, 3, 2, 6])

In [ ]:
np.mean(tab, axis= 1) # Moyenne de chaque ligne

array([5.66666667, 5.66666667, 6.33333333, 3.66666667, 7.        ])

In [ ]:
np.sum(tab, axis= 0) # somme de chque colonne

array([34, 33, 18])

## Cas d'analyse

In [ ]:
notes = np.random.randint(19, size=(10, 3))
notes

array([[12,  1,  6],
       [ 7, 14, 17],
       [ 5, 13,  8],
       [ 9, 16,  5],
       [15, 15,  0],
       [18,  3, 17],
       [14,  7,  0],
       [ 1,  9,  0],
       [10,  3, 11],
       [18,  2,  0]])

Chaque ligne représente les notes d'un étudiant en Maths, Physique et Biologie

In [ ]:
notes.shape

(10, 3)

Quelle est la moyenne dans chaque matière ?

In [ ]:
notes.mean(axis=0)
#np.mean(notes, axis=0)

array([10.9,  8.3,  6.4])

Quelle est la moyenne par étudiant ?

In [ ]:
moy_per_student = np.mean(notes, axis=1)
moy_per_student

array([ 6.33333333, 12.66666667,  8.66666667, 10.        , 10.        ,
       12.66666667,  7.        ,  3.33333333,  8.        ,  6.66666667])

Combien  d'étudiants ont une note supérieure à 10 :

In [ ]:
moy_per_student >= 10

array([False,  True, False,  True,  True,  True, False, False, False,
       False])

In [ ]:
np.sum([0, 1, 1, 0])

2

In [ ]:
np.sum([False,  True, True, False])

2

In [ ]:
np.sum(moy_per_student >= 10)

4

4 étudiants ont plus de 10.